M48
; DRILL file {KiCad 8.0.1} date 2024-04-22T11:34:42+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-22T11:34:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0236
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X7.874Y-2.8017
X7.9921Y-2.2835
T2
X7.6Y-2.48
X7.6Y-2.58
M30
